trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: "Terraform Init"
  inputs:
    targetType: inline
    script: |
      terraform init

- task: Bash@3
  displayName: "Terraform Plan"
  inputs:
    targetType: inline
    script: |
      terraform plan -out=tfplan

- task: Bash@3
  displayName: "Terraform Apply"
  inputs:
    targetType: inline
    script: |
      terraform apply -auto-approve tfplan
